Region.create(name: "Kanto")
Region.create(name: "Johto")
Region.create(name: "Hoenn")
Region.create(name: "Sinnoh")
Region.create(name: "Unova")
Region.create(name: "Kalos")
Region.create(name: "Alola")
